[[act_priv_spec_1_11]]
=== ACT Requirements for Privileged 1.11 Specification

*Version:* 0.2 +
*One line description:* This policy describes simplified Architectural
Compatibility Test (ACT) requirements for the privileged specification.
This policy is temporary and will be replaced by a standard ACT suite in
the future. +
*Author(s):* Greg Favor, Arun Thomas +
*Status:* Approved +

==== Version History

[width="100%",cols="<5%,<15%,<50%,<20%",options="header",]
|===
|Ver |Date |Details |Name(s)

|0.2 |2022-01-13 |added clarity on system emulators |Greg Favor
| |2021-09-02 |added clarity on ACT vs compatibility testing. |

|0.1 |2021-05-03 |Original draft |Greg Favor, Arun Thomas
|===

==== Rationale

https://docs.google.com/document/u/2/d/1ZKSLQ5HPT3E_CqTVOQlBPs7qJ9v1mpnMDXHhtOQJFcU/edit[Architectural
Compatibility Tests (ACT)] are required for Privileged Specification
v1.12 ratification. As there is no current ACT suite for Privileged
Specification v1.11 (let alone v1.12) and there is no plan to develop
them in time for ratification, this policy proposes an alternate
compatibility testing methodology based on running operating system and
hypervisor software that exercises new features added in Privileged
Specification 1.12.

==== Policy:

. In lieu of member’s running ACT suite for Privileged Specification
1.12 features which are intended to be used for compatibility,
implementations must run an operating system and hypervisor software (or
equivalent) using the extensions as a prerequisite to claim
compatibility with Privileged Specification 1.12. +
. TGs will not be required to develop ACT tests in order to pass
https://docs.google.com/document/u/2/d/1Hp9ZZSzjk6Tp2pIvh33mNCj6wAoJCEqsdENQUTSruQg/edit[DoD]
in 2021. +
. RISC-V International will provide OS and hypervisor patches that add
functionality for new Privileged Specification 1.12 features to be
exercised, including stc, Sccofpmf, Svnapot, Svinval, Svpbmt, Sv57, and
the H extension. For OS compatibility testing, RVI will provide Linux
kernel patches adding support for Privileged Specification 1.12. For
hypervisor compatibility testing, RVI will provide KVM and Xvisor
patches adding support for Privileged Specification 1.12. As there is
upstream Linux kernel support for Privileged Specification 1.11, no
additional patches will be required for Privileged specification 1.11
features. +
. To demonstrate compatibility, a compatible implementation must:

.. Boot a Linux distribution and run simple commands and small
benchmarks. +
.. Boot a Linux distribution and run simple commands and small
benchmarks in a virtual environment running on KVM. +
.. Boot a Linux distribution and run simple commands and small
benchmarks in a virtual environment running on Xvisor. +
. For practical runtime considerations, this is expected to be done on
either an FPGA, FPGA prototyping system, or emulation system (e.g. a
supported simulator). +
. One may shortcut the boot process wrt time-intensive steps that
repetitively perform an operation and do very little to utilize
significant Privileged specification features or exercise architectural
corner cases. +
. This policy is temporary and applies only to Privileged Specification
1.12 ratification.

==== Transition to start using policy: +
Immediate
