[[llvm_toochain_singoff]]
== LLVM Tool Chain Sign-Off Criteria

Specifies the criteria for acceptance of LLVM tool chain.

*Version:* 0.1 +
*Author(s):* Nidal Faour, Jeremy Bennett, Ed Jones +
*Status:* Draft +

*Version History:* +
[width="100%",cols="<5%,<15%,<50%,<20%",options="header",]
|===
|Ver |Date |Details |Name(s)

|0.1 |2021-05-03 |Pre-review draft |Nidal Faour, Jeremy Bennett, Ed Jones

|===

=== Rationale

Various task groups commission work to add LLVM toolchain support for
extensions and features. This policy provides a baseline set of sign-off
criteria. It also serves as a framework for other software projects
requiring sign-off criteria.

Components affected are Clang (driver/frontend), LLVM assembler, LLVM
linker (lld), LLVM IR, lldb, libcxx. Not all of these are necessarily
affected. Typically only C/C++ support is considered, but for some
projects, support for other languages may be appropriate.

=== Policy

. The project should have added regression (LLVM unit test, LLVM
internal, LLVM lit). +
. Tests in the following categories where relevant. +
.. Target-specific LLVM assembler and disassembler regression tests of
new instructions or assembler directives, including tests expected to
fail, testing boundary and median cases (llvm/test/MC/RISCV). When
appropriate testing must include tests of -march flag extensions to
verify new instructions are only available when the flag(s) is/are set
and that they are not available when not set. +
.. LLVM assembler target-specific regression tests to ensure correct
generation of any new relocations added (llvm/test/MC/RISCV). +
.. LLVM linker (lld) regression tests (lld/test/ELF) for any new
relocations supported by the LLVM linker. +
.. LLVM libcxx using LIT to run libcxx testsuits and running
benchmarks. +
.. LLVM Debugger (LLDB) test suite (LLDB unit tests, shell tests, API
tests) +
.. Clang driver/frontend tests for any changes to the command line
interface (flags, search directories, multilibs) and preprocessor
defines (tests in clang/test/Driver). +
.. Clang regression target-specific code generation tests for all new
builtins (clang/test/CodeGen/RISCV). +
.. LLVM code generation tests for any new intrinsic functions or changes
to instruction generation (llvm/test/CodeGen/RISCV). +
.. LLVM IR and code generation tests for any new RISCV-specific
optimizations (llvm/test/CodeGen/RISCV). +
. For LLVM compilers intended for use with application class processors,
the project should run the LLVM test suite, a collection of application
programs. +
. The project should have added the subset of the GCC regression test
suite suitable for use with Clang/LLM. The reason why many Clang/LLVM
ports do this is that the LLVM regression tests only test as far as IR,
there are no general execution tests (the LLVM test suite is a
collection of applications, but only runs on larger machines under
"full-fat" operating systems). +
. The project should have added GCC regression tests in the following
categories where relevant. +
.. GNU compiler target specific tests of all new code generation
patterns, builtins, intrinsic functions and preprocessor defines. +
.. GNU compiler C/C++ target specific regression tests of *-march* flag
extensions, both to verify that new builtins/intrinsics/preprocessor
defines are available when the flag(s) is/are set and that they are not
available when not set +
.. GNU compiler C/C++ target specific regression tests of libgcc and
newlib multilibs (these tests may belong here, or in the libraries) +
. Provide LLVM regression test results, GCC regression test results and
(where appropriate) LLVM test suite results, which should demonstrate no
new failures or unresolved tests compared to the upstream compiler and
with all added tests passing. Total new successes (passes or expected
failures) should match the number added above. +
. RISC-V architectural compliance tests (ACT) for underlying
architecture should pass (i.e. we haven’t done anything to break base
architectures). +
. Agreed benchmark results should be presented. The choice of benchmark
will depend on the specific project. For example
https://www.embench.org/[Embench] may be appropriate for a project
targeting small integer RV32 machines, but not for a project targeting
large multicore RV32G machines. General projects may require multiple
sets of benchmarks. +
. Any submitted patches must follow the
https://llvm.org/docs/CodingStandards.html[LLVM coding standards] .
Changes should be submitted according to the
https://llvm.org/docs/DeveloperPolicy.html[LLVM developer policy]. +
. An appropriate upstream code owner reviews and approves the patches.
Note: Anybody is allowed to review code for submission to the LLVM
project, but you should seek approval from a well-known RISC-V
contributor. If submitting a change which touches generic code, wait for
additional approval from a maintainer of that code (the LLVM developer
policy has a section on finding appropriate reviewers). For a large
change affecting other targets or many generic components, propose the
changes through an RFC to the llvm-dev mailing list and link to the
submitted patch. +
. The project must be signed off by the Toolchain & Runtimes SSC, who
have responsibility for coordination with other projects and can defer
that sign-off and responsibility to appropriate subcommittees.

=== Exception handling +
None

=== Transition to start using policy +
Immediate on approval

=== Next steps

. Review by T&R mailing list with timeout to the next T&R meeting. +
. Review of policy with recommendation by TSC & Chairs with a two week
timeout on immediately following next T&R meeting (extendable on request
by reviewers by two weeks). +
. Identify at least two specific people from TSC to review the policy
before it is approved. +
. Have the TSC chair and CTO review the proposal.

