[[question_response]]
=== Question Response 

*Version:* 1.1 +
*One line description:* Answer member questions reliably within a SLA and
identify who is responsible for ensuring questions are answered +
*Author(s):* Mark I Himelstein +
*Status:* Approved +

==== Version History

[width="100%",cols="<5%,<15%,<50%,<20%",options="header",]
|===
|Ver |Date |Details |Name(s)

|1.1 |2021-5-13 | Updates |Mark Himelstein

|1.0 |2020-08-10 |Original version |Mark Himelstein

|===

==== Rationale

This is a best practice. We need this policy because when people ask
questions to the general email lists sometimes no one responds.
Sometimes we don’t respond because we think someone else will or should
respond or we don’t have the time. The result is that without responses
specifications get delayed.

This policy is intended to least define the goals that we want groups,
committees and their chairs and vice-chairs to achieve. There is no
intent to enforce this in any way. Obviously there will be times that it
cannot or does not happen

==== Policy

This policy applies to any question from technical to procedural to
resources etc.

TSC, Chairs and each Standing Committee must provide a mechanism for
people to ask questions. That mechanism could be a person to email, a
group email list, jira, etc. as appropriate and in accordance with other
policies (like the github policy). The mechanism must be published on
github in the README.

The chairs of those groups should at least respond to emails within
24-48 hours M-F except on holidays (i.e. business days).

Responses can be one of three things: 

. answer and resolve the question, +
. notify the requester that the question belongs to another
group and CC that group who in turn should respond in accordance with
this policy or 
. acknowledge receipt of the question and tell the
responder when they should expect an answer by the chair or someone else
(it may take time to get someone to answer because they don’t have the
time or information or need to clarify the question, etc.) at some
(hopefully identified) period in the future.

The requester should try to pick an appropriate group and contact that
group directly and not always send email to chairs or tech. The
requester should also make it clear when they need an answer and any
appropriate background and rationale for the question (ask yourself what
the reader of the question is likely to ask when they get the question
and include it on the initial request instead of requiring iteration).

It is up to the chair of each group to make sure they or their delegate
respond appropriately in the time specified if possible in this policy.

The answer should be recorded in Jira or Github issues as appropriate
but may also include adding it to, for example, issues on
specifications.

Github is the official way to track specification Jira will be the
official way to track questions and responses in cross group
interactions.

The final resolution may be a discrete answer or that we choose as a
group to defer the question for a fixed time or indefinitely.

If requesters don’t know where to send a question they should do so to
help@riscv.org.

==== Exception handling +
Escalate to help@riscv.org if you don’t get a response after trying
twice.

Transition to start using policy: +
Acting policy as of August 10, 2020. Officially starts upon approval.

https://docs.google.com/document/d/1muwa9dkGSjnZmNxu6qH4zWZH92YVv6bHrJLRGs6185s/edit?usp=sharing[Download
Here]
