[[riscv_contributor]]
=== RISC-V Contributor

*Version:* 1.1 +
*One line description:* Who can contribute to RISC-V specifications +
*Author(s):* Mark Himelstein +
*Status:* Approved +

==== Version History

[width="100%",cols="<5%,<15%,<50%,<20%",options="header",]
|===
|Ver |Date |Details |Name(s)

|1.1 |2022-01-13 |Comment acceptance and cleanup for clarity. Add version history.
|Jeff Scheel

|1.0 |2021-04-29 |Original versio |Mark Himelstein

|===

==== Rationale

The RISC-V membership agreement covers IP topics. If contributors are
not members, then they are not bound by a technical contribution
agreement.

==== Policy

. Contributors to RISC-V specification text must have signed a member
agreement. +
. RISC-V staff will set the github maintainers to the chairs and vice
chairs only. Additional information can be found in the
https://docs.google.com/document/d/1TdUWp-OUIQjsWgip7bRfhZBuUC64Upf5eyfBj7fWd_Q/[GitHub
Repo Structure & Administration] policy. +
. Task Groups and Committees developing specifications should not allow
any pull requests from non-members (RISC-V staff will help likely using
the certificate of origin used by the linux kernel). +
. An audit must be done before a specification goes to public review as
to whether any pull requests got into the specification by non-members.
RISC-V staff will work to identify or develop utilities to assist in
this process +
. The CTO will sign-off that the review has been done as part of
https://docs.google.com/document/d/14ZpciYwIzmuiB92_hKfwTAttTnc3rsLbWI-CpC7MdC8/edit?usp=sharing[DoD].

==== Exception handling +
Not applicable

==== Transition to start using policy +
Immediately
